package com.competentum.demo.javacc.compiler;
import java.util.Map;

/* Generated By:JJTree: Do not edit this line. ASTBlock.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTBlock extends SimpleNode {
	public ASTBlock(int id) {
		super(id);
	}

	public ASTBlock(ExampleCompiler p, int id) {
		super(p, id);
	}

	@Override
	public AlgValue eval(Map<String, AlgValue> symbolTable) throws InterpreterException {
		for (int i = 0; i < jjtGetNumChildren(); i++)
			getChild(i).eval(symbolTable);
		return null;
	}
}
/*
 * JavaCC - OriginalChecksum=3b601927874aef1ebd46378d2528c975 (do not edit this
 * line)
 */
