package com.competentum.demo.javacc.compiler;
import java.util.Map;

/* Generated By:JJTree: Do not edit this line. ASTDivNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTDivNode extends SimpleNode {
	public ASTDivNode(int id) {
		super(id);
	}

	public ASTDivNode(ExampleCompiler p, int id) {
		super(p, id);
	}

	@Override
	public Value eval(Map<String, Value> symbolTable)throws InterpreterException {
		if(jjtGetNumChildren() < 1)
			throw new InterpreterException();
		Value value = getChild(0).eval(symbolTable);
		for (int i = 1; i < jjtGetNumChildren(); i++)
			value = div(value, getChild(i).eval(symbolTable));

		return value;
	}
	
	private Value div(Value a, Value b) throws InterpreterException {
		if(a == null || b == null)
			throw new InterpreterException();
		if(a.getType() == Type.INT && b.getType() == Type.INT)
			return new Value(Type.INT, (int)a.getValue() / (int)b.getValue());
		throw new InterpreterException();
	}

}
/*
 * JavaCC - OriginalChecksum=3a5a8f0afd07fcf0b59b9cae0a44c6ec (do not edit this
 * line)
 */
