package com.competentum.demo.javacc.compiler;
import java.util.Map;

/* Generated By:JJTree: Do not edit this line. ASTGTNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGTNode extends SimpleNode {
  public ASTGTNode(int id) {
    super(id);
  }

  public ASTGTNode(ExampleCompiler p, int id) {
    super(p, id);
  }
	@Override
	public Value eval(Map<String, Value> symbolTable) throws InterpreterException {
		if(jjtGetNumChildren() != 2)
			throw new IllegalStateException();
		Value a = getChild(0).eval(symbolTable);
		Value b = getChild(1).eval(symbolTable);
		if(a.getType() != Type.INT || b.getType() != Type.INT)
			throw new InterpreterException();
		return new Value(Type.BOOL, (int)a.getValue() > (int)b.getValue());
	}
}
/* JavaCC - OriginalChecksum=a78a2288f7c7c13e494bd61f864b43ed (do not edit this line) */
