package com.competentum.demo.javacc.compiler;
import java.util.Map;

/* Generated By:JJTree: Do not edit this line. ASTNotNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTNotNode extends SimpleNode {
	public ASTNotNode(int id) {
		super(id);
	}

	public ASTNotNode(ExampleCompiler p, int id) {
		super(p, id);
	}

	@Override
	public Value eval(Map<String, Value> symbolTable) throws InterpreterException {
		if(jjtGetNumChildren() != 1)
			throw new InterpreterException();
		Value value = getChild(0).eval(symbolTable);
		if(value.getType() != Type.BOOL)
			throw new InterpreterException();
		return new Value(Type.BOOL, !(boolean) value.getValue());
	}

}
/*
 * JavaCC - OriginalChecksum=0d1d2d94f781c43411cd1fa8e303cbc4 (do not edit this
 * line)
 */
