package com.competentum.demo.javacc.compiler;
import java.util.Map;

/* Generated By:JJTree: Do not edit this line. ASTPrint.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTPrint extends SimpleNode {
	public ASTPrint(int id) {
		super(id);
	}

	public ASTPrint(ExampleCompiler p, int id) {
		super(p, id);
	}

	@Override
	public AlgValue eval(Map<String, AlgValue> symbolTable) throws InterpreterException {
		System.out.println(getChild(0).eval(symbolTable).getValue());
		return null;
	}

}
/*
 * JavaCC - OriginalChecksum=28baeb82ffb3cc277c1ba77da14eb2e9 (do not edit this
 * line)
 */
