package com.competentum.demo.javacc.compiler;
import java.util.Map;

/* Generated By:JJTree: Do not edit this line. ASTStringLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTStringLiteral extends SimpleNode {

	protected String value;

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		value = value.substring(1, value.length() -1 );
		value = value.replaceAll("\\\\n", "\n").replaceAll("\\\\t", "\t");
		value = value.replaceAll("\\\\r", "\r").replaceAll("\\\\\"", "\"");
		value = value.replaceAll("\\\\\\\\", "\\\\");
		this.value = value;
	}

	public ASTStringLiteral(int id) {
		super(id);
	}

	public ASTStringLiteral(ExampleCompiler p, int id) {
		super(p, id);
	}

	@Override
	public AlgValue eval(Map<String, AlgValue> symbolTable) {
		return new AlgValue(Type.STRING, value);
	}

}
/*
 * JavaCC - OriginalChecksum=203e0a9007223a1489298f464216a7c1 (do not edit this
 * line)
 */
