package com.competentum.demo.javacc.compiler;
import java.util.Map;

/* Generated By:JJTree: Do not edit this line. ASTTrue.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTTrue extends SimpleNode {
	public ASTTrue(int id) {
		super(id);
	}

	public ASTTrue(ExampleCompiler p, int id) {
		super(p, id);
	}

	@Override
	public Value eval(Map<String, Value> symbolTable) {
		return new Value(Type.BOOL, true);
	}

}
/*
 * JavaCC - OriginalChecksum=59995fdfecf874ba6901795cd6f5c676 (do not edit this
 * line)
 */
