package com.competentum.demo.javacc.compiler;
import java.util.Map;

/* Generated By:JJTree: Do not edit this line. ASTWhile.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTWhile extends SimpleNode {
	public ASTWhile(int id) {
		super(id);
	}

	public ASTWhile(ExampleCompiler p, int id) {
		super(p, id);
	}

	@Override
	public AlgValue eval(Map<String, AlgValue> symbolTable)
			throws InterpreterException {
		if(jjtGetNumChildren() != 2)
			throw new InterpreterException();
		while (check(getChild(0).eval(symbolTable))) {
			getChild(1).eval(symbolTable);
		}
		return null;
	}

	private boolean check(AlgValue val) throws InterpreterException {
		if (val == null || val.getType() != Type.BOOL)
			throw new InterpreterException();
		return (boolean) val.getValue();
	}

}
/*
 * JavaCC - OriginalChecksum=98825f3dcbac864ac0f99bbc4c221f7a (do not edit this
 * line)
 */
