/* Generated By:JavaCC: Do not edit this line. ExampleCompilerTreeConstants.java Version 6.0_beta */
package com.competentum.demo.javacc.compiler;

public interface ExampleCompilerTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVARDECALARE = 1;
  public int JJTVOID = 2;
  public int JJTASSIGNMENT = 3;
  public int JJTORNODE = 4;
  public int JJTANDNODE = 5;
  public int JJTXORNODE = 6;
  public int JJTEQNODE = 7;
  public int JJTNEQNODE = 8;
  public int JJTLTNODE = 9;
  public int JJTGTNODE = 10;
  public int JJTLENODE = 11;
  public int JJTGENODE = 12;
  public int JJTADDNODE = 13;
  public int JJTMINUSNODE = 14;
  public int JJTMULNODE = 15;
  public int JJTDIVNODE = 16;
  public int JJTMODNODE = 17;
  public int JJTNOTNODE = 18;
  public int JJTUNARYMINUSNODE = 19;
  public int JJTIDENTIFIER = 20;
  public int JJTSTRINGLITERAL = 21;
  public int JJTINTLITERAL = 22;
  public int JJTTRUE = 23;
  public int JJTFALSE = 24;
  public int JJTBLOCK = 25;
  public int JJTIF = 26;
  public int JJTWHILE = 27;
  public int JJTPRINT = 28;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "VarDecalare",
    "void",
    "Assignment",
    "OrNode",
    "AndNode",
    "XorNode",
    "EQNode",
    "NEQNode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "MinusNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "NotNode",
    "UnaryMinusNode",
    "Identifier",
    "StringLiteral",
    "IntLiteral",
    "True",
    "False",
    "Block",
    "If",
    "While",
    "Print",
  };
}
/* JavaCC - OriginalChecksum=0138ebfa58754822fc5ca2f1616aa7f5 (do not edit this line) */
